
SELECT * FROM ORDERSSELECT * FROM SALESMANSELECT * FROM CUSTOMER1-- 1 -- SELECT ORD_NO , PURCH_AMT , ORD_DATE , CUSTOMER_ID , SALESMAN_IDFROM ORDERS O  INNER JOIN SALESMAN S ON O.SALESMAN_ID = S.SALESMANI_IDWHERE S.NAME='PAUL ADAM'--2--SELECT ORD_NO , PURCH_AMT , ORD_DATE , CUSTOMER_ID , SALESMAN_IDFROM ORDERS O  INNER JOIN SALESMAN S ON O.SALESMAN_ID = S.SALESMANI_IDWHERE S.CITY='LONDON'--3--SELECT ORD_NO , PURCH_AMT , ORD_DATE , CUSTOMER_ID , SALESMAN_IDFROM ORDERS O  INNER JOIN SALESMAN S ON O.SALESMAN_ID = S.SALESMANI_IDWHERE O.CUSTOMER_ID=3007--4--
SELECT * FROM ORDERSSELECT * FROM SALESMANSELECT   ORD_NO , PURCH_AMT , ORD_DATE , CUSTOMER_ID , SALESMAN_IDFROM ORDERS WHERE PURCH_AMT > (SELECT AVG(PURCH_AMT) FROM ORDERS WHERE ORD_DATE='10-OCT-2012')--5--SELECT ORD_NO , PURCH_AMT , ORD_DATE , CUSTOMER_ID , SALESMAN_IDFROM ORDERS O  INNER JOIN SALESMAN S ON O.SALESMAN_ID = S.SALESMANI_IDWHERE S.CITY='NEW YORK'--6--SELECT * FROM SALESMANSELECT COMMISSIONFROM  SALESMAN WHERE CITY='PARIS'Write a SQL query to determine the commission of the salespeople in Paris. Return commission.--7--SELECT * FROM SALESMANSELECT * FROM CUSTOMER1SELECT *FROM CUSTOMER1 WHERE CUSTOMERID = 3001Write a query to display all the customers whose ID is 3001 below the salesperson ID of Mc Lyon--8--SELECT * FROM ORDERSSELECT * FROM SALESMANSELECT * FROM CUSTOMER1------ GRADE NOT INSERTED --------------9--SELECT * FROM ORDERSSELECT * FROM SALESMANSELECT   ORD_NO , PURCH_AMT , ORD_DATE , CUSTOMER_ID , SALESMAN_IDFROM ORDERS  INNER JOIN SALESMAN ON ORDERS.SALESMAN_ID = SALESMAN.SALESMANI_IDWHERE SALESMAN.COMMISSION = (SELECT MAX(COMMISSION) FROM SALESMAN )Write a SQL query to find those salespeople who earned the maximum commission. Return ord_no,
purch_amt, ord_date, and salesman_id
--10--
SELECT * FROM ORDERSSELECT * FROM CUSTOMER1

SELECT ORD_NO , PURCH_AMT , ORD_DATE , CUSTOMER_ID , SALESMAN_ID ,C.CUSTOMERNAMEFROM ORDERS O  INNER JOIN CUSTOMER C ON O.CUSTOMER_ID = C.CUSTOMERIDWHERE ORD_DATE='17-AUG-2012'

. Write SQL query to find the customers who placed orders on 17th August 2012. Return ord_no, purch_amt,
ord_date, customer_id, salesman_id and cust_name.
--11--
SELECT * FROM ORDERSSELECT * FROM SALESMAN

SELECT NAME  FROM SALESMAN

. Write a SQL query to find salespeople who had more than one customer. Return salesman_id and name