CREATE TABLE STUDENT1 (
	RNO INT,
	NAME VARCHAR(50),
	CITY VARCHAR(50),
	DID INT 
)

CREATE TABLE ACADEMIC(
	RNO INT ,
	SIP DECIMAL(8,2),
	BKLOG INT 
)

CREATE TABLE DEPARTMENT1(
	DID INT ,
	DNAME VARCHAR(50)
)

INSERT INTO STUDENT1 VALUES(101, 'Raju', 'Rajkot', 10);

INSERT INTO STUDENT1 VALUES(102, 'Amit', 'Ahmedabad', 20);

INSERT INTO STUDENT1 VALUES(103, 'Sanjay', 'Baroda', 40);

INSERT INTO STUDENT1 VALUES(104, 'Neha', 'Rajkot', 20);

INSERT INTO STUDENT1 VALUES(105, 'Meera', 'Ahmedabad', 30);

INSERT INTO STUDENT1 VALUES(106, 'Mahesh', 'Baroda',10);

INSERT INTO ACADEMIC VALUES(101, 8.8, 0);

INSERT INTO ACADEMIC VALUES(102, 9.2, 2);

INSERT INTO ACADEMIC VALUES(103, 7.6, 1);
INSERT INTO ACADEMIC VALUES(104, 8.2, 4);
INSERT INTO ACADEMIC VALUES(105, 7.0, 2);
INSERT INTO ACADEMIC VALUES(106, 8.9, 3);

INSERT INTO DEPARTMENT1 VALUES(10, 'Computer');
INSERT INTO DEPARTMENT1 VALUES(20, 'Electrical');
INSERT INTO DEPARTMENT1 VALUES(30, 'Mechanical');
INSERT INTO DEPARTMENT1 VALUES(40, 'Civil');

SELECT * FROM STUDENT1
SELECT * FROM ACADEMIC 
SELECT * FROM DEPARTMENT1

--1--
SELECT * FROM STUDENT1 S
WHERE S.DID =
(SELECT DID FROM DEPARTMENT1 WHERE DNAME = 'COMPUTER' )

--2--
SELECT NAME 
FROM STUDENT1 
WHERE RNO IN 
(SELECT RNO FROM ACADEMIC WHERE SIP>8)

--3--
SELECT * FROM STUDENT1  
WHERE CITY='RAJKOT' AND DID IN
(SELECT DID FROM DEPARTMENT1  WHERE DNAME='COMPUTER')

--4--
SELECT * FROM STUDENT1
SELECT * FROM DEPARTMENT1

SELECT COUNT(DID) FROM STUDENT1 
WHERE DID IN 
(SELECT DID FROM DEPARTMENT1 WHERE  DNAME='ELECTRICAL')

--5--
SELECT * FROM STUDENT1
SELECT * FROM ACADEMIC 

SELECT NAME FROM STUDENT1 WHERE RNO IN 
(SELECT TOP 1 RNO FROM ACADEMIC
 ORDER BY SIP DESC)
--6--
SELECT * FROM STUDENT1
SELECT * FROM ACADEMIC
Display details of students having more than 1 backlog.

SELECT * FROM STUDENT1 WHERE RNO IN (
SELECT RNO FROM ACADEMIC WHERE BKLOG > 1)

--7--
SELECT * FROM STUDENT1
SELECT * FROM ACADEMIC
Display name of student who is having second highest SPI.

SELECT * FROM STUDENT1 
WHERE RNO IN (
	select top 1 rno from ACADEMIC WHERE RNO IN (
		select TOP 2 RNO FROM ACADEMIC
		ORDER BY SIP DESC 
	)
	ORDER BY SIP 
) 
--8--
SELECT * FROM STUDENT1
SELECT * FROM DEPARTMENT1

. Display name of students who are either from computer department or from mechanical department.

SELECT * FROM STUDENT1 
WHERE DID IN (
	SELECT DID FROM DEPARTMENT1 
	WHERE DNAME IN ('COMPUTER ' , 'MECHANICAL')
)

--9-- 
SELECT * FROM STUDENT1 
WHERE DID IN(
	SELECT DID FROM STUDENT1
	WHERE RNO>102	
)
--10--SELECT * FROM STUDENT1 WHERE RNO IN(	SELECT RNO FROM ACADEMIC WHERE SIP>9)AND DID IN (SELECT DID FROM DEPARTMENT1 WHERE DNAME='ELECTRICAL')